services:
  web:
    image: php:8.3-apache
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        ports:
            - "8080:81"
        volumes:
            - ./src:/var/www/html
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: 123456
        volumes:
            - sqlserver_data:/var/opt/mssql

volumes:
    sqlserver_data:
