services:
  web:
    build:
      # El 'context' es la carpeta desde donde Docker va a trabajar. 
      # Dejamos el punto (.) para que tenga acceso a toda la raíz de tu proyecto.
      context: .
      # Aquí le indicamos la ruta exacta de dónde leer las instrucciones
      dockerfile: .docker/php/Dockerfile
    container_name: mi_app_php
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html